name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write # minimal for Actions to create releases

jobs:
  create-release:
    name: Build and Create Tagged Release
    runs-on: ubuntu-latest

    steps:
      # Install zip for packaging
      - name: Install archive tools
        run: sudo apt install zip -y

      # Checkout repo
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      # Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      # Set environment variables
      - name: Get variables
        id: get_vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%D')" >> $GITHUB_ENV

      # Install dependencies
      - name: Install dependencies
        run: bun install --frozen-lockfile

      # Bump package version (without creating git tag)
      - name: Bump package version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version ${{ github.ref_name }} --no-git-tag

      # Run build
      - name: Run build
        run: bun run build

      # Commit & push changes using PAT
      - name: Update repository
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Use the Personal Access Token (PAT)
          git remote set-url origin https://x-access-token:${{ secrets.GH_PUSH_TOKEN }}@github.com/${{ github.repository }}.git

          git add .
          git commit -m '${{ github.ref_name }}'
          git push origin ${{ github.ref_name }} --tags

      # Bundle files into a zip
      - name: Bundle files
        run: |
          zip -r ${{ github.event.repository.name }}.zip . -x "./.*" "./node_modules/*" "./scripts/*" "./src/*" "./web/*" "./tsconfig.json" "./bun.lock" "./package.json" "./biome.json"

      # Create release using the zip
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        id: auto_release
        with:
          repo_token: "${{ secrets.GH_PUSH_TOKEN }}"
          title: "${{ github.ref_name }}"
          prerelease: false
          files: ${{ github.event.repository.name }}.zip

        env:
          CI: false
